swagger: "2.0"
info:
  title: ArgentBank Transactions API
  description: API pour gérer les transactions des utilisateurs
  version: "1.0.0"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

security:
  - Bearer: []

paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Utilisateur
      summary: Obtenir la liste des transactions
      description: API pour récupérer toutes les transactions d'un utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: Liste des transactions introuvable
        '500':
          description: Erreur interne du serveur

  /user/profile/transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Utilisateur
      summary: Obtenir une transaction par ID
      description: API pour récupérer une transaction spécifique d'un utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: integer
          required: true
          description: ID de la transaction à récupérer
      produces:
        - application/json
      responses:
        '200':
          description: Transaction récupérée avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: ID invalide fourni
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur

    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Utilisateur
      summary: Mettre à jour une transaction existante
      description: API pour mettre à jour une transaction utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: integer
          required: true
          description: ID de la transaction à mettre à jour
        - in: body
          name: body
          description: Données mises à jour pour la transaction utilisateur
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Champs invalides
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      transactionData:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          details:
            type: object
            properties:
              type:
                type: string
              category:
                type: string
              notes:
                type: string

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
